[build]
  # Default settings for your React app
  command = "npm run build"
  publish = "dist"  # Vite output directory

[context.storybook]
  command = "npm run build:sb"  # Build Storybook
  publish = "storybook-static"  # Storybook output directory
